name: Deploy to Production

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Gemini-API 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use secret from environment
        env: 
          VITE_API_KEY: ${{ secrets.API_KEY }}
        run: npm run dev